# Generated by Django 2.1.8 on 2019-05-03 08:29

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', slugger.fields.AutoSlugField(allow_unicode=True, populate_from='title', unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='클라이언트')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='작업기간')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '작업들',
                'ordering': ['-updated'],
            },
        ),
    ]
